import { jsPDF } from 'jspdf';
import type { AuditReadinessSummary } from './auditReadiness';

export type AuditPackPdfInput = {
  companyName: string;
  siteLabel?: string;
  dateFrom: Date;
  dateTo: Date;
  summary: AuditReadinessSummary;
  jobCount: number;
  chemicalSummary: string[];
  primaryColor?: string;
  footerText?: string;
};

export function buildAuditPackSummaryPdf(input: AuditPackPdfInput): Buffer {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const color = input.primaryColor ?? '#2563EB';
  doc.setFillColor(37, 99, 235);
  if (color.startsWith('#') && color.length === 7) {
    doc.setFillColor(
      parseInt(color.slice(1, 3), 16),
      parseInt(color.slice(3, 5), 16),
      parseInt(color.slice(5, 7), 16),
    );
  }
  doc.rect(0, 0, 210, 24, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text('Audit pack summary', 14, 14);
  doc.setFontSize(10);
  doc.text(input.companyName, 14, 20);

  doc.setTextColor(30, 41, 59);
  let y = 34;
  doc.text(`Period: ${input.dateFrom.toLocaleDateString('en-GB')} – ${input.dateTo.toLocaleDateString('en-GB')}`, 14, y);
  y += 8;
  if (input.siteLabel) {
    doc.text(`Site: ${input.siteLabel}`, 14, y);
    y += 8;
  }
  doc.setFontSize(14);
  doc.text(`Compliance score: ${input.summary.complianceHealth.score}/100`, 14, y);
  y += 10;
  doc.setFontSize(10);
  doc.text(`Completed jobs in window: ${input.summary.reportCount}`, 14, y);
  y += 6;
  doc.text(`Missing signatures: ${input.summary.missingSignatures}`, 14, y);
  y += 6;
  doc.text(`Expiring qualifications (90d): ${input.summary.expiringQualifications}`, 14, y);
  y += 6;
  doc.text(`Open compliance issues: ${input.summary.openComplianceIssues}`, 14, y);
  y += 10;
  doc.text('Warnings:', 14, y);
  y += 6;
  for (const w of input.summary.complianceHealth.warnings.slice(0, 8)) {
    doc.text(`• ${w.title}: ${w.count}`, 18, y);
    y += 5;
  }
  y += 6;
  doc.text(`Total jobs exported: ${input.jobCount}`, 14, y);
  y += 8;
  if (input.chemicalSummary.length > 0) {
    doc.text('Recent chemical usage:', 14, y);
    y += 6;
    for (const line of input.chemicalSummary.slice(0, 10)) {
      doc.text(`• ${line.slice(0, 70)}`, 18, y);
      y += 5;
    }
  }
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(input.footerText ?? 'Generated by Pest Trace — audit-ready compliance export.', 14, 285);
  return Buffer.from(doc.output('arraybuffer'));
}
